apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: dev-eks-cluster
  region: ap-northeast-2

iam:
  withOIDC: true

vpc:
  subnets:
    public:
      ap-northeast-2a:
        id: subnet-0f87f1cff15470a6c
      ap-northeast-2b:
        id: subnet-09c60ccdab1ac38cc
    private:
      ap-northeast-2a:
        id: subnet-09c3bf06e5645a29d
      ap-northeast-2b:
        id: subnet-0de53ebb9fdf0f710

cloudWatch:
  clusterLogging:
    enableTypes: ["*"]

fargateProfiles:
    - name: dev-eks-fargate
      subnets:
        - subnet-09c3bf06e5645a29d
        - subnet-0de53ebb9fdf0f710
      selectors:
        - namespace: "*"
        - namespace: kube-system
